version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: achref0011
      MYSQL_DATABASE: rental-cars
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - backend-network

  spring:
    image: mohamed0x/rental-car.jar:1.1.0
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/rental-cars?createDatabaseIfNotExist=true
    volumes:
      - spring_data:/app/data
    depends_on:
      - mysql
    networks:
      - backend-network

networks:
  backend-network:
volumes:
  mysql_data:
  mysql_config:
  spring_data:
  angular_data: